spring.application.name=sistema-farmacia

spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_farmacia
spring.datasource.username=postgres
spring.datasource.password=951753

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
